Customer Ticket 1
NewForce-at-Mountwest/bangazonapi-team-horrohawk pull request #2
Opened 2019-12-11 16:15 UTC by Jengwen

## Proposed changes
This is the build to run the Customer Controller and it's associated tests. You can now Get a list of All Customers, Get a single customer, Add a customer, and edit a customer.
You can also query to include a list of all customers with their payment types, or query to include a list of customers with their list of products for sale, or query for a customer's last name or first name with a string of included letters.  You can also test customers Get All method, Get a single, post and put methods.

## Related Issues

## Steps To Test
To get a list of customers:
Start the application, in the browser type "http://localhost:63540/api/customer" you should see a list of customers
To get a single customer:
in the browser type "http://localhost:63540/api/customer/6"
you should see a customer by the name of Fred Smith
To query to include a list of payment types:
in the browser type "http://localhost:63540/api/customer?include=payments"
You should see Sally Jones and Bob Robertson with a list of their payment types
To query to include a list of products for sale by a customer
in the browser type "http://localhost:63540/api/customer?include=products"
You will then see Sally Jones with a list of her products for sale as well as Bob Robertson with his products for sale 
To test POST Method:
Type http://localhost:63540/api/customer and change dropdown to POSTT in Postmaster and the following into the body in Postman 
{
"firstName": "Judy",
"lastName": "Dench"
} hit send and get all customers again with http://localhost:63540/api/customer in the browser
you should now see your new customer in the customer list
To test PUT Method
Type http://localhost:63540/api/customer and change dropdown to PUT in Postmaster and the following into the body in Postman 
{
"firstName": "Jane",
} hit send and get all customers again with http://localhost:63540/api/customer in the browser
you should now see your edited customer name in the list

You can also select Test and Run all Tests in Visual Studio to see successful tests

## What kind of change does this PR introduce?
Please check one of the following:
- [ ] Bug fix
- [ ] Documentation update
- [ x] New feature
- [ ] Other

2019-12-11 18:42 UTC, LanceP51 commented
need to go to Appsettings and remove "01" from SQLServer address.
need to use customer/4 when trying out the PUT method

works well, without issues
Jen will be changing this SQL setting so we wont have to worry with this in the future

2019-12-11 18:58 UTC, Tommy-Spurlock requested changes
Please include SQL script data needed to run test.

2019-12-11 19:11 UTC, Jengwen commented
The SQL script is now in the testing instructions

2019-12-11 19:57 UTC, Tommy-Spurlock requested changes
When I tried to run the SQL script it threw errors concerning foreign key constraints. Check to see if your SQL script needs any additional information. 
*When running the get all at `/api/customer` I received 7 items.
* `include=products` threw an error. 
* When running `PUT` in postman I received a 400 error. 

I believe these are all errors related to the SQL script seed data. You may need to include a SQL command that will recreate the database and tables before seeding data.

2019-12-12 14:07 UTC, Jengwen commented
Updated the SQL script to correct table issues.

2019-12-12 16:27 UTC, LanceP51 commented on BangazonAPITest/CustomerControllerTests.cs
> +                // Make sure we got back a 200 OK Status and that there are more than 0 coffees in our database
coffee?

2019-12-12 16:27 UTC, LanceP51 commented on BangazonAPITest/CustomerControllerTests.cs
> +                // Try to get all of the students from /api/customer
student?

2019-12-12 16:28 UTC, LanceP51 commented on BangazonAPITest/CustomerControllerTests.cs
> +        // Reusable method to deelte a customer from the database
deelte?

2019-12-12 16:28 UTC, LanceP51 commented on BangazonAPITest/CustomerControllerTests.cs
> +        // Reusable method to create a new student in the database and return it
student? or customer?

2019-12-12 16:28 UTC, LanceP51 commented on BangazonAPITest/CustomerControllerTests.cs
> +        public async Task Update_Student()
student?

2019-12-12 16:29 UTC, LanceP51 commented on BangazonAPITest/CustomerControllerTests.cs
> +                // Make a new title and assign it to our dummy student
student?

2019-12-12 16:30 UTC, LanceP51 reviewed
please correct typos

2019-12-12 19:28 UTC, Tommy-Spurlock requested changes
Include=products returned both sally jones and Fred Smith twice. The testing instructions for`PUT` only include firstName and should also include lastName 
`{
"firstName": "Jane",
"lastName": "Dench"
}`.    Almost There!!!

2019-12-13 14:34 UTC, AllxnCook commented
functions on my machine
saw no errors in the process of testing
all tests passed
great job!

2019-12-13 14:35 UTC, merged